In [2]:
import pandas as pd
from pandas import Series

In [3]:
pd.__version__

'1.5.3'

In [4]:
obj = Series([73, 51, -15, 13])
obj

0    73
1    51
2   -15
3    13
dtype: int64

In [5]:
type(obj)

pandas.core.series.Series

In [6]:
obj.values

array([ 73,  51, -15,  13], dtype=int64)

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = Series([73, 51, -5, 13], index= ['a', 'b', 'c', 'd'])
obj2

a    73
b    51
c    -5
d    13
dtype: int64

In [10]:
obj2.values

array([73, 51, -5, 13], dtype=int64)

In [11]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
novo_obj = obj2.append(Series([100, 10000], index= ['e', 'f']))
novo_obj  

C:\Users\Samsung\AppData\Local\Temp\ipykernel_760\1144598664.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  novo_obj = obj2.append(Series([100, 1000], index= ['e', 'f']))


a      73
b      51
c      -5
d      13
e     100
f    1000
dtype: int64

In [14]:
h = obj2[obj2 > 10]
h

a    73
b    51
d    13
dtype: int64

In [15]:
obj2['a']

73

In [16]:
'e' in obj2

False

In [17]:
dict = {'Apple': 408.25, 'Amazon': 249.25, 'Microsoft': 210.19, 'Google': 196.81, 'Samsung': 74.36}

In [18]:
obj3 = Series(dict)
obj3

Apple        408.25
Amazon       249.25
Microsoft    210.19
Google       196.81
Samsung       74.36
dtype: float64

In [19]:
empresas = ['Apple', 'Amazon', 'Microsoft', 'Google', 'Coca-cola']


In [20]:
obj4 = Series(dict, index= empresas)
obj4

Apple        408.25
Amazon       249.25
Microsoft    210.19
Google       196.81
Coca-cola       NaN
dtype: float64

In [21]:
pd.isnull(obj4)

Apple        False
Amazon       False
Microsoft    False
Google       False
Coca-cola     True
dtype: bool

In [22]:
pd.notnull(obj4)

Apple         True
Amazon        True
Microsoft     True
Google        True
Coca-cola    False
dtype: bool

In [23]:
obj3 + obj4

Amazon       498.50
Apple        816.50
Coca-cola       NaN
Google       393.62
Microsoft    420.38
Samsung         NaN
dtype: float64

In [24]:
obj4.name = 'Valiosas'

In [25]:
obj4.index.name = 'Empresas'

In [27]:
print(obj4)

Empresas
Apple        408.25
Amazon       249.25
Microsoft    210.19
Google       196.81
Coca-cola       NaN
Name: Valiosas, dtype: float64

In [29]:
obj3 = obj3.append(Series([325.7], index=['Coca-Cola']))
obj3

C:\Users\Samsung\AppData\Local\Temp\ipykernel_760\863098803.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  obj3 = obj3.append(Series([325.7], index=['Coca-Cola']))


Apple        408.25
Amazon       249.25
Microsoft    210.19
Google       196.81
Samsung       74.36
Coca-Cola    325.70
dtype: float64

In [30]:
obj5 = obj3.append(Series([45.12, 12.36, 21], index=['Facebook', 'Linux', 'Twitter']))
obj5

C:\Users\Samsung\AppData\Local\Temp\ipykernel_760\1461717056.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  obj5 = obj3.append(Series([45.12, 12.36, 21], index=['Facebook', 'Linux', 'Twitter']))


Apple        408.25
Amazon       249.25
Microsoft    210.19
Google       196.81
Samsung       74.36
Coca-Cola    325.70
Facebook      45.12
Linux         12.36
Twitter       21.00
dtype: float64

In [31]:
from pandas import DataFrame

data = data = {'Estado': ['Santa Catarina', 'Paraná', 'Goiás', 'Bahia', 'Minas Gerais'], 
        'Ano': [2002, 2003, 2004, 2005, 2006], 
        'População': [1.5, 1.7, 3.6, 2.4, 2.9]}

meuDf = pd.DataFrame(data)
meuDf

Estado   Ano  População
0  Santa Catarina  2002        1.5
1          Paraná  2003        1.7
2           Goiás  2004        3.6
3           Bahia  2005        2.4
4    Minas Gerais  2006        2.9

In [32]:
meuDf.shape

(5, 3)

In [33]:
type(meuDf)

pandas.core.frame.DataFrame

In [34]:
DataFrame(data, columns = ['Ano', 'Estado', 'População'])


Ano          Estado  População
0  2002  Santa Catarina        1.5
1  2003          Paraná        1.7
2  2004           Goiás        3.6
3  2005           Bahia        2.4
4  2006    Minas Gerais        2.9

In [67]:
frame2 = DataFrame(data, columns = ['Ano', 'Estado', 'População', 'Área'], index = ['um', 'dois', 'três', 'quatro', 'cinco'])
frame2

Ano          Estado  População Área
um      2002  Santa Catarina        1.5  NaN
dois    2003          Paraná        1.7  NaN
três    2004           Goiás        3.6  NaN
quatro  2005           Bahia        2.4  NaN
cinco   2006    Minas Gerais        2.9  NaN

In [68]:
estados = frame2['Estado']
estados

um        Santa Catarina
dois              Paraná
três               Goiás
quatro             Bahia
cinco       Minas Gerais
Name: Estado, dtype: object

In [41]:
frame2.index

Index(['um', 'dois', 'três', 'quatro', 'cinco'], dtype='object')

In [42]:
frame2.columns

Index(['Ano', 'Estado', 'População', 'Area'], dtype='object')

In [43]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, nan],
       [2003, 'Paraná', 1.7, nan],
       [2004, 'Goiás', 3.6, nan],
       [2005, 'Bahia', 2.4, nan],
       [2006, 'Minas Gerais', 2.9, nan]], dtype=object)

In [44]:
frame2['Ano']


um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [45]:
frame2.Ano

um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [46]:
frame2[:2]

Ano          Estado  População Area
um    2002  Santa Catarina        1.5  NaN
dois  2003          Paraná        1.7  NaN

In [47]:
print(frame2[3:])
print(frame2[-2:])
print(frame2[2:4])

         Ano        Estado  População Area
quatro  2005         Bahia        2.4  NaN
cinco   2006  Minas Gerais        2.9  NaN
         Ano        Estado  População Area
quatro  2005         Bahia        2.4  NaN
cinco   2006  Minas Gerais        2.9  NaN
         Ano Estado  População Area
três    2004  Goiás        3.6  NaN
quatro  2005  Bahia        2.4  NaN


In [70]:
import numpy as np 



In [51]:
frame2

Ano          Estado  População Area
um      2002  Santa Catarina        1.5  NaN
dois    2003          Paraná        1.7  NaN
três    2004           Goiás        3.6  NaN
quatro  2005           Bahia        2.4  NaN
cinco   2006    Minas Gerais        2.9  NaN

In [69]:
frame2['Área'] = np.random.randint(1, 10, 5)
frame2

Ano          Estado  População  Área
um      2002  Santa Catarina        1.5     4
dois    2003          Paraná        1.7     7
três    2004           Goiás        3.6     7
quatro  2005           Bahia        2.4     6
cinco   2006    Minas Gerais        2.9     5

In [58]:
frame2.describe()

Ano  População
count     5.000000   5.000000
mean   2004.000000   2.420000
std       1.581139   0.864292
min    2002.000000   1.500000
25%    2003.000000   1.700000
50%    2004.000000   2.400000
75%    2005.000000   2.900000
max    2006.000000   3.600000

In [61]:
frame2['quatro':'cinco']

Ano        Estado  População Area
quatro  2005         Bahia        2.4  NaN
cinco   2006  Minas Gerais        2.9  NaN

In [65]:
frame2[frame2['População'] < 2.5]


Ano          Estado  População Area
um      2002  Santa Catarina        1.5  NaN
dois    2003          Paraná        1.7  NaN
quatro  2005           Bahia        2.4  NaN

In [72]:
a = frame2[frame2['População']>= 2.5]
b = a[a['Área']>= 5.]
b

Ano        Estado  População  Área
três   2004         Goiás        3.6     7
cinco  2006  Minas Gerais        2.9     5

In [73]:
frame2.loc['quatro']


Ano           2005
Estado       Bahia
População      2.4
Área             6
Name: quatro, dtype: object

In [74]:
frame2.iloc[3]

Ano           2005
Estado       Bahia
População      2.4
Área             6
Name: quatro, dtype: object